const numberButtons = documnet.querySelectorAll('[data-number]')
const operationButtons = documnet.querySelectorAll('[data-operation]')
const equalButton = documnet.querySelector('[data-equals]')
const deleteButton = documnet.querySelector('[data-delete]')
const allClearButton = documnet.querySelector('[data-all-clear]')
const perviousOperand = documnet.querySelector('[data-previous-operand]')
const currentOperand = documnet.querySelector('[data-current-operand]')
